// Localization configuration
// Generated by flutter_gen, do not edit manually

import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

// Supported locales
const List<Locale> supportedLocales = [
  Locale('ru'),
  Locale('uk'),
  Locale('en'),
  Locale('ar'),
];

// Locale resolution callback
LocaleResolutionCallback localeResolutionCallback = (locale, supportedLocales) {
  if (locale == null) {
    return supportedLocales.first;
  }
  
  for (final supportedLocale in supportedLocales) {
    if (supportedLocale.languageCode == locale.languageCode) {
      return supportedLocale;
    }
  }
  
  return supportedLocales.first;
};

// Helper to get current locale direction
TextDirection getLocaleDirection(Locale locale) {
  if (locale.languageCode == 'ar') {
    return TextDirection.rtl;
  }
  return TextDirection.ltr;
}

// Extension for easy localization access
extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this)!;
}